
server:
  port: 8050


mybatis-plus:
  type-aliases-package: cn.hyx.bg.entity
  mapper-locations: classpath:/mapper/*Mapper.xml

spring:
  datasource:
    url: jdbc:mysql://rm-wz9ov0f403gi9b9shro.mysql.rds.aliyuncs.com:3306/bg_data?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=true
    username: hyx
    password: h8986345@
    driver-class-name: com.mysql.cj.jdbc.Driver

